force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>VIS-{000000}</displayFormat>
        <label>Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Follow_Up__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Follow Up Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Representative__c.field-meta.xml
<CustomField>
    <fullName>Representative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Representative</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VisitService.cls
public with sharing class VisitService {

    public static void beforeInsert(List<Visit__c> visits){

    for(Visit__c visit : visits){
			system.debug('=======Visit Trigger Start');
        if(visit.Representative__c == null){
            visit.Representative__c = UserInfo.getUserId();
            system.debug('representative=' +userInfo.getUserId());
        }

        if(String.isBlank(visit.Status__c)){
            visit.Status__c = VisitConstants.STATUS_PLANNED;
            system.debug('Visit Status=' + VisitConstants.STATUS_PLANNED);
        }

        if(visit.Visit_Date__c == null){
            visit.Visit_Date__c = Date.today();
            system.debug('Visit Date=' + visit.Visit_Date__c);
        }
        
        if(visit.Follow_Up__c == True){
            visit.Next_Visit_Date__c = Date.today().addDays(7);
            system.debug('===Follow Up Task Created======');
        }

    }

}

    public static void beforeUpdate(
    List<Visit__c> visits,
    Map<Id,Visit__c> oldMap
){

    for(Visit__c visit : visits){

        Visit__c oldVisit = oldMap.get(visit.Id);

        if(
            oldVisit.Status__c == VisitConstants.STATUS_COMPLETED &&
            visit.Status__c == VisitConstants.STATUS_PLANNED
        ){
			system.debug('Completed visits cannot be changed back to Planned.');
            visit.addError(
                'Completed visits cannot be changed back to Planned.'
            );

        }

    }

}

    public static void afterInsert(List<Visit__c> visits){

    List<Task> tasks = new List<Task>();

    for(Visit__c visit : visits){

        if(visit.Follow_Up__c){

            Task t = new Task();

            t.Subject = 'Follow up Visit';

            t.WhatId = visit.Id;

            t.OwnerId = visit.Representative__c;

            t.ActivityDate = Date.today().addDays(7);

            tasks.add(t);

        }

    }

    if(!tasks.isEmpty()){

        insert tasks;

    }

}

    public static void afterUpdate(
    List<Visit__c> visits,
    Map<Id,Visit__c> oldMap
){

    for(Visit__c visit : visits){

        Visit__c oldVisit = oldMap.get(visit.Id);

        if(
            oldVisit.Status__c != VisitConstants.STATUS_COMPLETED &&
            visit.Status__c == VisitConstants.STATUS_COMPLETED
        ){

            System.debug(
                'Visit Completed : Ready for AI Processing'
            );

        }

    }

}
}